name: Main
on:
  schedule:
    - cron:  '0 6 * * *'
  push:
    paths-ignore:
      - '**.md'
    branches:
      - develop
      - main
  pull_request:
  workflow_dispatch:
jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "home-assistant/actions/hassfest@master"
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: asdf_install
        uses: asdf-vm/actions/install@v3
      - name: Install Python modules
        run: |
          pip install -r requirements.test.txt
      - name: Unit tests suite
        run: |
          python -m pytest tests/unit
      - name: Integration tests suite
        run: |
          python -m pytest tests/integration
  release:
    name: Release
    if: github.ref == 'refs/heads/main'
    needs:
    - validate
    - test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: asdf_install
        uses: asdf-vm/actions/install@v3
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release
      - name: Merge main into develop
        uses: devmasx/merge-branch@master
        with:
          type: now
          message: "chore: Merged main into develop"
          from_branch: main
          target_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
