name: Main
on:
  schedule:
    - cron:  '0 1 * * *'
  push:
    branches:
      - develop
      - main
  pull_request:
jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "home-assistant/actions/hassfest@master"
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
  release:
    name: Release
    if: github.ref == 'refs/heads/main'
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: asdf_install
        uses: asdf-vm/actions/install@v1
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release
      - name: Merge main into develop
        uses: devmasx/merge-branch@master
        with:
          type: now
          message: "chore: Merged main into develop"
          from_branch: main
          target_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
